name: Golang Build and Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # github.repository as <account>/<repo>
  LOG_LEVEL: DEBUG

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        go build -o medusa-api ./cmd/medusa-api/main.go
        go build -o medusa-engine ./cmd/medusa-engine/main.go
        go build -o medusa-daemon ./cmd/medusa-daemon/main.go
    - name: Test
      run: go test -v ./...
